version: '3'

services:

  viz:
    image: dockersamples/visualizer
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4040:8080

