version: '3.5'

services:

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - frontend
    deploy:
      endpoint_mode: dnsrr

  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      endpoint_mode: dnsrr

  vote:
    image: bretfisher/examplevotingapp_vote
    networks:
      - frontend
      - proxy
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=vote.dogvs.cat
        - com.df.port=80
 
  result:
    image: bretfisher/examplevotingapp_result
    networks:
      - backend
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=result.dogvs.cat
        - com.df.port=80
 
  worker:
    image: bretfisher/examplevotingapp_worker:java
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2

networks:
  frontend: {}
  backend: {}
  proxy:
    external: true

volumes:
  db-data:
    driver: rexray/dobs
    driver_opts:
      size: 1
  redis-data:
    driver: rexray/dobs
    driver_opts:
      size: 1

