version: "3.7"

# 1. WORKAROUND: would prefer this use null network driver, will use bride for now to avoid overlay
# 2. TODO: would prefer on-failure restart_policy, but need to run this in script to look
# for if plugin exists first before reinstalling
# 3. TODO: would prefer this picks a driver version, and support driver updates

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  plugin-rexray:
    <<: *default-opts
    image: mavenugo/swarm-exec:17.03.0-ce
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: docker plugin install --grant-all-permissions rexray/dobs DOBS_REGION=nyc3 DOBS_TOKEN="${REXRAY_DO_TOKEN}" DOBS_CONVERTUNDERSCORES=true
    # TODO: make token a secret
    deploy:
      mode: global
      restart_policy:
        condition: none

networks:
  bridge:
    external: true
    name: bridge
