version: '3.4'

services:

  menu:
    image: bretfisher/dogvscat-menu
    build:
      context: menu
    deploy:
      replicas: 3
      labels:
        - traefik.port=80
        - traefik.docker.network=proxy
        - traefik.frontend.rule=Host:www.dogvs.cat,dogvs.cat
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5000"
    networks:
      - proxy

networks:
  proxy:
    external: true

