version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:

  menu:
    <<: *default-opts
    image: dogvscat/menu
    build:
      context: menu
    deploy:
      replicas: 3
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:www.dogvs.cat,dogvs.cat
    networks:
      - proxy

networks:
  proxy:
    external: true

