version: '3.5'

services:

  ghost:
    image: ghost:1-alpine
    networks:
      - proxy
      - ghost
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: OpdP2dy4jzAT
      database__connection__database: ghost
      url: http://ghost.dogvs.cat
    deploy:
      replicas: 1
      labels:
        - traefik.port=2368
        - traefik.docker.network=proxy
        - traefik.frontend.rule=Host:ghost.dogvs.cat
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5000"

  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db-password
    networks:
      - ghost
    deploy:
      endpoint_mode: dnsrr
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5000"
        
networks:
  ghost: {}
  proxy:
    external: true

volumes:
  db:
    driver: rexray/dobs
    driver_opts:
      size: 1

secrets:
  db-password:
    file: ./secret-ghost-db



